include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: true
    prefer_relative_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_pub_dependencies: true
